# Generated by Django 3.1.4 on 2021-11-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211106_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.IntegerField(default=int, max_length=10000000),
            preserve_default=False,
        ),
    ]
