# Generated by Django 3.1.4 on 2021-11-06 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_blogpost_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like_post',
            field=models.ManyToManyField(related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
