# Generated by Django 3.1.4 on 2021-11-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211106_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='like_post',
            field=models.IntegerField(max_length=4000),
        ),
    ]
