# Generated by Django 3.1.4 on 2021-11-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211106_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='like_post',
            new_name='_like_post',
        ),
    ]
