# Generated by Django 3.1.4 on 2021-11-06 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20211106_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='like_post',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='like',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
